# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_portal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8089
spring.jpa.show-sql=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rg2960889@gmail.com
spring.mail.password=sacrg2960889  # Use an environment variable for password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional SSL Configuration for Mail
# If the SSL/TLS handshake fails, make sure your JVM has the required certificates
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true
