name: Java Test Pipeline

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Verify Database Connection
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} -e "SELECT 1"

      - name: Install Dependencies & Run Tests
        run: mvn clean test