name: Java Test Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4.4
        env:
          MYSQL_DATABASE: vehicle_portal
          MYSQL_ROOT_PASSWORD: root_password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run tests
        run: ./mvnw test

      - name: Stop MySQL service
        run: |
          docker stop ${{ job.services.mysql.id }}
          docker rm ${{ job.services.mysql.id }}

      - name: Remove Docker network
        run: docker network rm github_network_${{ github.run_id }}